package utils;

import java.util.HashMap;
import java.util.Map;

public class CountryCodeMapper {

    private static final Map<String, String> countryNameToCode = new HashMap<>();

    static {
        // All 195+ countries with their international dialing codes
        countryNameToCode.put("Afghanistan", "+93");
        countryNameToCode.put("Albania", "+355");
        countryNameToCode.put("Algeria", "+213");
        countryNameToCode.put("Andorra", "+376");
        countryNameToCode.put("Angola", "+244");
        countryNameToCode.put("Antigua and Barbuda", "+1");
        countryNameToCode.put("Argentina", "+54");
        countryNameToCode.put("Armenia", "+374");
        countryNameToCode.put("Australia", "+61");
        countryNameToCode.put("Austria", "+43");
        countryNameToCode.put("Azerbaijan", "+994");
        countryNameToCode.put("Bahamas", "+1");
        countryNameToCode.put("Bahrain", "+973");
        countryNameToCode.put("Bangladesh", "+880");
        countryNameToCode.put("Barbados", "+1");
        countryNameToCode.put("Belarus", "+375");
        countryNameToCode.put("Belgium", "+32");
        countryNameToCode.put("Belize", "+501");
        countryNameToCode.put("Benin", "+229");
        countryNameToCode.put("Bhutan", "+975");
        countryNameToCode.put("Bolivia", "+591");
        countryNameToCode.put("Bosnia and Herzegovina", "+387");
        countryNameToCode.put("Botswana", "+267");
        countryNameToCode.put("Brazil", "+55");
        countryNameToCode.put("Brunei", "+673");
        countryNameToCode.put("Bulgaria", "+359");
        countryNameToCode.put("Burkina Faso", "+226");
        countryNameToCode.put("Burundi", "+257");
        countryNameToCode.put("Cambodia", "+855");
        countryNameToCode.put("Cameroon", "+237");
        countryNameToCode.put("Canada", "+1");
        countryNameToCode.put("Cape Verde", "+238");
        countryNameToCode.put("Central African Republic", "+236");
        countryNameToCode.put("Chad", "+235");
        countryNameToCode.put("Chile", "+56");
        countryNameToCode.put("China", "+86");
        countryNameToCode.put("Colombia", "+57");
        countryNameToCode.put("Comoros", "+269");
        countryNameToCode.put("Congo", "+242");
        countryNameToCode.put("Costa Rica", "+506");
        countryNameToCode.put("Croatia", "+385");
        countryNameToCode.put("Cuba", "+53");
        countryNameToCode.put("Cyprus", "+357");
        countryNameToCode.put("Czech Republic", "+420");
        countryNameToCode.put("Denmark", "+45");
        countryNameToCode.put("Djibouti", "+253");
        countryNameToCode.put("Dominica", "+1");
        countryNameToCode.put("Dominican Republic", "+1");
        countryNameToCode.put("Ecuador", "+593");
        countryNameToCode.put("Egypt", "+20");
        countryNameToCode.put("El Salvador", "+503");
        countryNameToCode.put("Equatorial Guinea", "+240");
        countryNameToCode.put("Eritrea", "+291");
        countryNameToCode.put("Estonia", "+372");
        countryNameToCode.put("Eswatini", "+268");
        countryNameToCode.put("Ethiopia", "+251");
        countryNameToCode.put("Fiji", "+679");
        countryNameToCode.put("Finland", "+358");
        countryNameToCode.put("France", "+33");
        countryNameToCode.put("Gabon", "+241");
        countryNameToCode.put("Gambia", "+220");
        countryNameToCode.put("Georgia", "+995");
        countryNameToCode.put("Germany", "+49");
        countryNameToCode.put("Ghana", "+233");
        countryNameToCode.put("Greece", "+30");
        countryNameToCode.put("Grenada", "+1");
        countryNameToCode.put("Guatemala", "+502");
        countryNameToCode.put("Guinea", "+224");
        countryNameToCode.put("Guinea-Bissau", "+245");
        countryNameToCode.put("Guyana", "+592");
        countryNameToCode.put("Haiti", "+509");
        countryNameToCode.put("Honduras", "+504");
        countryNameToCode.put("Hungary", "+36");
        countryNameToCode.put("Iceland", "+354");
        countryNameToCode.put("India", "+91");
        countryNameToCode.put("Indonesia", "+62");
        countryNameToCode.put("Iran", "+98");
        countryNameToCode.put("Iraq", "+964");
        countryNameToCode.put("Ireland", "+353");
        countryNameToCode.put("Israel", "+972");
        countryNameToCode.put("Italy", "+39");
        countryNameToCode.put("Jamaica", "+1");
        countryNameToCode.put("Japan", "+81");
        countryNameToCode.put("Jordan", "+962");
        countryNameToCode.put("Kazakhstan", "+7");
        countryNameToCode.put("Kenya", "+254");
        countryNameToCode.put("Kiribati", "+686");
        countryNameToCode.put("Kuwait", "+965");
        countryNameToCode.put("Kyrgyzstan", "+996");
        countryNameToCode.put("Laos", "+856");
        countryNameToCode.put("Latvia", "+371");
        countryNameToCode.put("Lebanon", "+961");
        countryNameToCode.put("Lesotho", "+266");
        countryNameToCode.put("Liberia", "+231");
        countryNameToCode.put("Libya", "+218");
        countryNameToCode.put("Liechtenstein", "+423");
        countryNameToCode.put("Lithuania", "+370");
        countryNameToCode.put("Luxembourg", "+352");
        countryNameToCode.put("Madagascar", "+261");
        countryNameToCode.put("Malawi", "+265");
        countryNameToCode.put("Malaysia", "+60");
        countryNameToCode.put("Maldives", "+960");
        countryNameToCode.put("Mali", "+223");
        countryNameToCode.put("Malta", "+356");
        countryNameToCode.put("Marshall Islands", "+692");
        countryNameToCode.put("Mauritania", "+222");
        countryNameToCode.put("Mauritius", "+230");
        countryNameToCode.put("Mexico", "+52");
        countryNameToCode.put("Micronesia", "+691");
        countryNameToCode.put("Moldova", "+373");
        countryNameToCode.put("Monaco", "+377");
        countryNameToCode.put("Mongolia", "+976");
        countryNameToCode.put("Montenegro", "+382");
        countryNameToCode.put("Morocco", "+212");
        countryNameToCode.put("Mozambique", "+258");
        countryNameToCode.put("Myanmar", "+95");
        countryNameToCode.put("Namibia", "+264");
        countryNameToCode.put("Nauru", "+674");
        countryNameToCode.put("Nepal", "+977");
        countryNameToCode.put("Netherlands", "+31");
        countryNameToCode.put("New Zealand", "+64");
        countryNameToCode.put("Nicaragua", "+505");
        countryNameToCode.put("Niger", "+227");
        countryNameToCode.put("Nigeria", "+234");
        countryNameToCode.put("North Korea", "+850");
        countryNameToCode.put("North Macedonia", "+389");
        countryNameToCode.put("Norway", "+47");
        countryNameToCode.put("Oman", "+968");
        countryNameToCode.put("Pakistan", "+92");
        countryNameToCode.put("Palau", "+680");
        countryNameToCode.put("Palestine", "+970");
        countryNameToCode.put("Panama", "+507");
        countryNameToCode.put("Papua New Guinea", "+675");
        countryNameToCode.put("Paraguay", "+595");
        countryNameToCode.put("Peru", "+51");
        countryNameToCode.put("Philippines", "+63");
        countryNameToCode.put("Poland", "+48");
        countryNameToCode.put("Portugal", "+351");
        countryNameToCode.put("Qatar", "+974");
        countryNameToCode.put("Romania", "+40");
        countryNameToCode.put("Russia", "+7");
        countryNameToCode.put("Rwanda", "+250");
        countryNameToCode.put("Saint Kitts and Nevis", "+1");
        countryNameToCode.put("Saint Lucia", "+1");
        countryNameToCode.put("Saint Vincent and the Grenadines", "+1");
        countryNameToCode.put("Samoa", "+685");
        countryNameToCode.put("San Marino", "+378");
        countryNameToCode.put("Sao Tome and Principe", "+239");
        countryNameToCode.put("Saudi Arabia", "+966");
        countryNameToCode.put("Senegal", "+221");
        countryNameToCode.put("Serbia", "+381");
        countryNameToCode.put("Seychelles", "+248");
        countryNameToCode.put("Sierra Leone", "+232");
        countryNameToCode.put("Singapore", "+65");
        countryNameToCode.put("Slovakia", "+421");
        countryNameToCode.put("Slovenia", "+386");
        countryNameToCode.put("Solomon Islands", "+677");
        countryNameToCode.put("Somalia", "+252");
        countryNameToCode.put("South Africa", "+27");
        countryNameToCode.put("South Korea", "+82");
        countryNameToCode.put("South Sudan", "+211");
        countryNameToCode.put("Spain", "+34");
        countryNameToCode.put("Sri Lanka", "+94");
        countryNameToCode.put("Sudan", "+249");
        countryNameToCode.put("Suriname", "+597");
        countryNameToCode.put("Sweden", "+46");
        countryNameToCode.put("Switzerland", "+41");
        countryNameToCode.put("Syria", "+963");
        countryNameToCode.put("Taiwan", "+886");
        countryNameToCode.put("Tajikistan", "+992");
        countryNameToCode.put("Tanzania", "+255");
        countryNameToCode.put("Thailand", "+66");
        countryNameToCode.put("Timor-Leste", "+670");
        countryNameToCode.put("Togo", "+228");
        countryNameToCode.put("Tonga", "+676");
        countryNameToCode.put("Trinidad and Tobago", "+1");
        countryNameToCode.put("Tunisia", "+216");
        countryNameToCode.put("Turkey", "+90");
        countryNameToCode.put("Turkmenistan", "+993");
        countryNameToCode.put("Tuvalu", "+688");
        countryNameToCode.put("Uganda", "+256");
        countryNameToCode.put("Ukraine", "+380");
        countryNameToCode.put("United Arab Emirates", "+971");
        countryNameToCode.put("United Kingdom", "+44");
        countryNameToCode.put("United States", "+1");
        countryNameToCode.put("Uruguay", "+598");
        countryNameToCode.put("Uzbekistan", "+998");
        countryNameToCode.put("Vanuatu", "+678");
        countryNameToCode.put("Vatican City", "+379");
        countryNameToCode.put("Venezuela", "+58");
        countryNameToCode.put("Vietnam", "+84");
        countryNameToCode.put("Yemen", "+967");
        countryNameToCode.put("Zambia", "+260");
        countryNameToCode.put("Zimbabwe", "+263");
    }

    public static String getCountryCode(String countryName) {
        return countryNameToCode.getOrDefault(countryName, "+91"); // default India
    }

}
