name: Daily Test Run

on:
  schedule:
    # 5:00 AM IST = 11:30 PM UTC (previous day)
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Project
        run: mvn clean install -DskipTests=false

      - name: Run TestNG Suite
        run: mvn test -DsuiteXmlFile=testng.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Upload Extent Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: test-output/
